### ISSUE TITLE
不太好用啊

### ISSUE THREAD

**Issue by jay6697117** [lyh0371/web-norm#10]
试了一下不太好用啊，没有自动化格式校验不说，基本的模板工程也没

**Comment by lyh0371** [comment]
自动化格式有的。这个不是模板工程项目，是给原有项目或者新建项目添加前端规范

**Comment by lyh0371** [comment]
@jay6697117 自动化格式有的。这个不是模板工程项目，是给原有项目或者新建项目添加前端规范
