### ISSUE TITLE
pnpm i 报错 Unmet peer dependencies

### ISSUE THREAD

**Issue by githubmoxie** [lyh0371/web-norm#11]
- 系统：windows 10
- node：v16.17.0
- 项目使用pnpm web-norm 之前依赖：
![1](https://user-images.githubusercontent.com/90609166/194695312-19d40453-b0f3-40eb-a8f7-052a5ace68d1.jpg)

使用命令后，pnpm i 出现错误
![2](https://user-images.githubusercontent.com/90609166/194695339-7a5c5a31-3528-43a2-aa45-8d5e2f11af32.jpg)

**Comment by githubmoxie** [comment]
好像不是包的原因，自己手动安装eslint，出现下面的报错，还没找到原因😅。
![图片](https://user-images.githubusercontent.com/90609166/194698604-4b2fbe96-ce87-43f6-870f-28c9dc631e13.jpg)

**Comment by lyh0371** [comment]
@githubmoxie  使用 yarn试试呢

**Comment by githubmoxie** [comment]
yarn 与 pnpm 一样的。
手动安装eslint解决了，原因是项目没有安装ts的原因。Does your project use TypeScript? · No / Yes（这个选错了，选No没事）
web-norm项目只能支持ts版本的，原因可能是一样的。
