### ISSUE TITLE
提交报错乱码了

### ISSUE THREAD

**Issue by rancho-xjq** [lyh0371/web-norm#12]
window
vue3
git提交的时候，报错乱码了
![image](https://user-images.githubusercontent.com/55220313/212796541-f4f12038-271e-4905-bc93-b6c955923611.png)

**Comment by lyh0371** [comment]
是文件名上面有中文吗？ 可以加我微信 lyh1347635797 我给你看下。

**Comment by lyh0371** [comment]
@rancho-xjq 是文件名上面有中文吗？ 可以加我微信 lyh1347635797 我给你看下。

**Comment by joesdu** [comment]
> window vue3 git提交的时候，报错乱码了 ![image](https://user-images.githubusercontent.com/55220313/212796541-f4f12038-271e-4905-bc93-b6c955923611.png)

建议使用Windows Terminal和Powershell Core
