### ISSUE TITLE
运行npm run commit 会报错

### ISSUE THREAD

**Issue by cy0926** [lyh0371/web-norm#13]
![image](https://user-images.githubusercontent.com/26456398/218272301-ea88d644-9d4f-49d5-9e5b-3d811cb64ab6.png)

怀疑是这个文件的报错，应该怎么修改呢
![image](https://user-images.githubusercontent.com/26456398/218272342-90080a01-8b01-4108-8881-752efcafbb44.png)

**Comment by lyh0371** [comment]
@cy0926  参考这个文章：https://blog.csdn.net/u012757419/article/details/105614028

**Comment by cy0926** [comment]
剩下这种报错了
![image](https://user-images.githubusercontent.com/26456398/218273475-fd204a8f-3431-4e3b-b83b-380b1fe3879b.png)

**Comment by cy0926** [comment]
问题已解决：
问题猜测：公司有加密软件，把node_modules下的部分文件加密了，导致启动不了项目，我之前将node_modules文件夹上传到远程仓库的方式来解决被加密的问题，所以每次使用nom run commit 命令的时候，都会去检查node_modules下所有的文件，导致lint-staged的检查通不过
解决方案：
需要手动执行命令，git rm --cached node_modules，取消对这个文件的跟踪，暂存区没有这个文件了就可以正常提交了
【注意】：一开始就避免将node_modules上传到远程分支，就能避免这个问题
附上成功截图：
![image](https://user-images.githubusercontent.com/26456398/218298997-0493b23a-d6fb-44d8-994c-564d80895554.png)

**Comment by lyh0371** [comment]
@cy0926  很棒
