### ISSUE TITLE
执行npm run commit 的时候报错

### ISSUE THREAD

**Issue by RuoFeng2015** [lyh0371/web-norm#3]
![image](https://user-images.githubusercontent.com/41161634/181180214-9ac857e0-ac65-4af1-9ed8-99ea8d3ea891.png)

**Comment by lyh0371** [comment]
如果是 mac电脑 运行 npm run postinstallmac 试试，window 电脑可能需要自己重新装下husky

**Comment by lyh0371** [comment]
可参考我的这篇文章 https://juejin.cn/post/7124196350446534670#heading-4

**Comment by moka-erb** [comment]
> 可参考我的这篇文章 https://juejin.cn/post/7124196350446534670#heading-4

按照里面常见问题操作后
出现这个错 /usr/bin/env: ‘sh’: No such file or directory

**Comment by lyh0371** [comment]
@moka-erb @RuoFeng2015 最新版本已修复

**Comment by moka-erb** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
