### ISSUE TITLE
react eslint 配置支持

### ISSUE THREAD

**Issue by a8655099449** [lyh0371/web-norm#5]
![image](https://user-images.githubusercontent.com/58685483/181695051-675e65a7-ac1f-45d6-ae95-d46868311059.png)

eslint的双引错误，好像会在jsx中生效，导致一大片的报错

**Comment by lyh0371** [comment]
感谢反馈  .eslintrc.js 文件，去掉  'jsx-quotes': [2, 'prefer-single'] 就可以了
