### ISSUE TITLE
少安装了一个依赖

### ISSUE THREAD

**Issue by xianyue0224** [lyh0371/web-norm#6]
![image](https://user-images.githubusercontent.com/83801486/182021880-bb6eea8a-04f0-4616-83ba-1b86af592ba7.png)
win11，Vue3-ts
执行web-norm命令之后，pnpm Install，会报缺少一个依赖，
Peer dependencies that should be installed:
  inquirer@^8.0.0
如果安装的时候，不指定它的版本，就会下载到9以上的版本，然而9版本在commit的时候会有问题，安装回8版本之后没问题。

**Comment by xianyue0224** [comment]
脚手架是vite3

**Comment by lyh0371** [comment]
感谢反馈，我试一下

**Comment by lyh0371** [comment]
@xianyue0224 感谢反馈，我试下

**Comment by lyh0371** [comment]
@xianyue0224 按照以上环境测试后未复现问题，但并不代表没有问题，如果有小伙伴遇到这个问题，可以参考以上解决方案。
