### ISSUE TITLE
自定义配置以及右键配置

### ISSUE THREAD

**Issue by cMing1997** [lyh0371/web-norm#7]
感觉这个可以帮助新项目省很多力气
作者有想过将这个弄到老项目的场景嘛？比如支持自定义是保存时格式化，还是右键点击格式化
或者提示报错的信息，是否支持自定义与默认合并组成最终的验证格式化规则

**Comment by lyh0371** [comment]
老项目的话可以文档中我也给出了方案https://github.com/lyh0371/web-norm#%E5%9C%A8%E8%80%81%E9%A1%B9%E7%9B%AE%E4%B8%AD%E4%BD%BF%E7%94%A8

**Comment by lyh0371** [comment]
@CasualMing 老项目的话我也给出了解决方案 [点击查看](https://github.com/lyh0371/web-norm#%E5%9C%A8%E8%80%81%E9%A1%B9%E7%9B%AE%E4%B8%AD%E4%BD%BF%E7%94%A8);至于你说的点击右键格式和... 我觉得应该开发一个vscode插件来实现了，并不是web-norm的能力范畴

**Comment by cMing1997** [comment]
> @CasualMing 老项目的话我也给出了解决方案 [点击查看](https://github.com/lyh0371/web-norm#%E5%9C%A8%E8%80%81%E9%A1%B9%E7%9B%AE%E4%B8%AD%E4%BD%BF%E7%94%A8);至于你说的点击右键格式和... 我觉得应该开发一个vscode插件来实现了，并不是web-norm的能力范畴

这个其实我想说的是，有的时候在老项目进行维护的时候，虽然想做一些 规范操作，但是也是得循序渐进嘛，像你那配置的保存就格式化，支持可配置会更好一些的

**Comment by lyh0371** [comment]
@CasualMing 哦 那这个功能是有的，需要修改生成的 .vacode settings.json 中的 editor.formatOnSave=false ,这样就不会自动保存了， 右键格式化vscode自带的有，如果项目中配置的有pretter 他就会按照配置文件自动格式化。
