### ISSUE TITLE
项目结构出现了mac独有的`.DS_Store`

### ISSUE THREAD

**Issue by Yamiqu** [lyh0371/web-norm#9]
你好，对这个项目比较感兴趣。
在fork之后，看了下好像是没有配置`.gitignore`，导致文件中有一些`.DS_Store`和`yarn-error`这类的冗余文件也在项目中。

于是提交了个PR https://github.com/lyh0371/web-norm/pull/8 ，配置了一下文件。

**Comment by lyh0371** [comment]
@Yamiqu 已merge
